hapiversion: 1.0.0

auto: true
pygments: true
server: true
server_port: 8080
permalink: /:categories/:title
lsi: false
exclude: ["package.json", "Gruntfile.js", "README.md"]

markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "lax_spacing", "with_toc_data"]